#-------------------------------
# General Site Settings
baseURL = "https://ericakn.github.io/blog/"
languageCode = "en-pt"
title = "Iridaceae"
theme = "Aditu"

#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 3

 # [[menu.main]]
 #   identifier = "styleguide"
 #   name = "Style Guide"
 #   url = "/styleguide"
 #   weight = 4


[params]
  logo = "images/Iridacea.jpg" 
  description = "Erica's website"

  [params.author]
    name = "Érica Kamimura Nishimura"
    avatar = "/blog/images/avatar.jpg"

  #-------------------------------
  # Hero Settings
  [params.hero]
    hero__title = "Hi there, I'm Érica"
    hero__description = "Data Scientist/ Data Engineer, \nEnvironmental Engineer and Sociology undergrad"
    hero__image = "/blog/images/background.jpg"

  [[params.social]]
    icon = "ion-logo-linkedin"
    name = "Linkedin"
    link = "https://www.linkedin.com/in/%C3%A9rica-k-nishimura-2b1ab535/"

 # [[params.social]]
 #   icon = "ion-icon-mail"
